#pragma once

enum class SoundTrack : int
{
	SE_PLAYER_PL_WALK = 0,
	SE_PLAYER_PL_SWORD = 1,
	SE_VOICE_PL_ATTACK_LONG = 5,
	SE_VOICE_PL_ATTACK_MIDDLE = 6,
	SE_VOICE_PL_ATTACK_SHORT = 7,
	SE_BOSS_GROUND = 8,
	SE_BOSS_ARACORE_VOICE = 9,
	SE_BOSS_IMPACT = 10,
	SE_BOSS_JUMP = 11,
	BGM_CAVE_AMBIENT = 12,
	BGM_CHASE = 13,
	SE_BOSS_DIE = 14,
	SE_CRYSTAL_C_BREAK_LARGE = 15,
	SE_CRYSTAL_C_BREAK_SMALL = 16,
	SE_DEER_DIE = 17,
	SE_DEER_LOOKIN = 18,
	SE_PLAYER_PL_WALK_GRASS = 19,
	SE_PLAYER_PL_WALK_ROCK = 20,
};
