; SOUND TRACK MANAGER
[tracks]
0=Resources/Sound/SE/Player/pl_walk.wav
1=Resources/Sound/SE/Player/pl_sword.wav
5=Resources/Sound/SE/Voice/pl_attack_long.wav
6=Resources/Sound/SE/Voice/pl_attack_middle.wav
7=Resources/Sound/SE/Voice/pl_attack_short.wav
8=Resources/Sound/SE/Boss/ground.wav
9=Resources/Sound/SE/Boss/aracore_voice.wav
10=Resources/Sound/SE/Boss/impact.wav
11=Resources/Sound/SE/Boss/jump.wav
12=Resources/Sound/BGM/cave_ambient.wav
13=Resources/Sound/BGM/chase.wav
14=Resources/Sound/SE/Boss/die.wav
15=Resources/Sound/SE/Crystal/c_break_large.wav
16=Resources/Sound/SE/Crystal/c_break_small.wav
17=Resources/Sound/SE/Deer/die.wav
18=Resources/Sound/SE/Deer/lookin.wav
19=Resources/Sound/SE/Player/pl_walk_grass.wav
20=Resources/Sound/SE/Player/pl_walk_rock.wav
