; CACHE MANAGER
; Resources/Image images preload by default

[resources/ai/enemysmall.json]
exclude=0
preload=0

[resources/ai/spiderchase.json]
exclude=0
preload=0

[resources/font/arialuni.ttf]
exclude=0
preload=1

[resources/font/fa-solid-900.ttf]
exclude=0
preload=1

[resources/image/bugtex.dds]
exclude=1
preload=0

[resources/image/bugtex.png]
exclude=0
preload=1

[resources/image/fog_particle.png]
exclude=0
preload=1

[resources/image/loading.png]
exclude=0
preload=1

[resources/image/particle256x256.png]
exclude=0
preload=1

[resources/image/test.png]
exclude=0
preload=1

[resources/licenses/tuxalin-water-shader-license.txt]
exclude=1
preload=0

[resources/model/teststage.vmdl]
exclude=0
preload=1

[resources/physicslayers.physicslayers]
exclude=0
preload=1

[resources/sound/tracks/0.vsnd]
exclude=0
preload=0

[resources/sound/tracks/1.vsnd]
exclude=0
preload=0

[resources/sound/tracks/10.vsnd]
exclude=0
preload=0

[resources/sound/tracks/11.vsnd]
exclude=0
preload=0

[resources/sound/tracks/5.vsnd]
exclude=0
preload=0

[resources/sound/tracks/6.vsnd]
exclude=0
preload=0

[resources/sound/tracks/7.vsnd]
exclude=0
preload=0

[resources/sound/tracks/8.vsnd]
exclude=0
preload=0

[resources/sound/tracks/9.vsnd]
exclude=0
preload=0

[resources/stage/cave_01.vstg]
exclude=0
preload=0

[resources/ui/arrow.png]
exclude=0
preload=1

[resources/ui/circle.png]
exclude=0
preload=1

[resources/ui/guage.png]
exclude=0
preload=1

[resources/ui/header.png]
exclude=0
preload=1

[resources/ui/loading.png]
exclude=0
preload=1

[resources/ui/pause_selection.png]
exclude=0
preload=1

[resources/ui/title.png]
exclude=0
preload=1

[resources/ui/window.png]
exclude=0
preload=1
